---
- name: Create /docker-private-registry if it does not exist
  ansible.builtin.file:
    path: /docker-private-registry
    state: directory
    mode: '0755'

- name: Copy Docker compose file
  template:
    src: docker-compose.yml.j2
    dest: /docker-private-registry/docker-compose.yml
    mode: 0664

- name: Tear down existing services
  community.docker.docker_compose:
    project_src: /docker-private-registry
    state: absent

- name: Create and start registry service
  community.docker.docker_compose:
    project_src: /docker-private-registry
  register: output

- ansible.builtin.debug:
    var: output