---
- name: Container Registry on Ubuntu
  hosts: container-registry
  gather_facts: True
  become: True
  vars:
    vault_addr: "{{ lookup('ansible.builtin.env', 'VAULT_ADDR') }}"
    vault_token: "{{ lookup('ansible.builtin.env', 'VAULT_TOKEN') }}"

  roles:
    - role: common
      vars:
        hostname: cr.teokyllc.internal

    - role: docker

    - role: registry
      vars:
        is_mirror: false
        mirror_url: https://registry-1.docker.io
        tls_ttl: 8035h
        tls_common_name: cr.teokyllc.internal
        cr_admin_user: ataylor

  tasks:
    - name: Reboot the container registry
      ansible.builtin.reboot: