---
- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Add Hashicorp GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /etc/apt/trusted.gpg.d/hashicorp.asc
    mode: '0644'
    force: true

- name: Add Hashicorp Repository
  apt_repository:
    repo: deb https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    state: present
    filename: hashi
    mode: 0600

- name: Update packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install packages
  ansible.builtin.apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - jq
    - lsb-release
    - python3-pip
    - vault

- name: Install Python docker
  ansible.builtin.pip:
    name: docker
    executable: pip3

- name: Install Python yaml
  ansible.builtin.pip:
    name: pyyaml
    executable: pip3

- name: Add CA cert to trust store
  ansible.builtin.shell: |
    export VAULT_ADDR={{ vault_addr }}
    export VAULT_TOKEN={{ vault_token }}
    vault kv get -mount=kv -field=ca-chain cert > /usr/local/share/ca-certificates/root-ca-bundle.crt
    update-ca-certificates

- name: Add Vault SSH client signer public key
  ansible.builtin.shell: |
    curl -o /etc/ssh/trusted-user-ca-keys.pem {{ vault_addr }}/v1/ssh-client-signer/public_key
    echo "TrustedUserCAKeys /etc/ssh/trusted-user-ca-keys.pem" >> /etc/ssh/sshd_config