---
- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Add Hashicorp GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /etc/apt/trusted.gpg.d/hashicorp.asc
    mode: '0644'
    force: true

- name: Add Hashicorp Repository
  apt_repository:
    repo: deb https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    state: present
    filename: hashi
    mode: 0600

- name: Update packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install packages
  ansible.builtin.apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - lsb-release
    - python3-pip
    - vault

- name: Install Python docker
  ansible.builtin.pip:
    name: docker
    executable: pip3

- name: Install Python yaml
  ansible.builtin.pip:
    name: pyyaml
    executable: pip3