name: Run Ansible

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - 'main'
    paths:
      - '*/**'
  push:
    branches:
      - 'main'
    paths:
      - '*/**'

env:
  VAULT_ADDR: "https://vault.teokyllc.internal:8200"
  VAULT_TOKEN: ${{secrets.VAULT_TOKEN}}

jobs:
  run-ansible:
    name: Run Ansible playbook
    runs-on: [self-hosted]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Ansible
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -P ""
          vault write ssh-client-signer/sign/signer-role public_key=@$HOME/.ssh/id_rsa.pub
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook -i inventory --private-key signed-cert.pub --private-key ~/.ssh/id_rsa --user allan main.yml